/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Palette {
  $schema?: string;
  id: string;
  extends?: string;
  variables: {
    code?: {
      comment?: string;
      constant?: string;
      "constant.builtin"?: string;
      "constant.character"?: string;
      "constant.character.escape"?: string;
      "constant.numeric"?: string;
      "constant.other"?: string;
      entity?: string;
      "entity.name"?: string;
      "entity.name.class"?: string;
      "entity.name.function"?: string;
      "entity.name.method"?: string;
      "entity.name.section"?: string;
      "entity.name.tag"?: string;
      "entity.name.type"?: string;
      "entity.other.attribute-name"?: string;
      "entity.other.inherited-class"?: string;
      invalid?: string;
      "invalid.deprecated"?: string;
      "invalid.illegal"?: string;
      keyword?: string;
      "keyword.control"?: string;
      "keyword.control.import"?: string;
      "keyword.operator"?: string;
      "keyword.other"?: string;
      markup?: string;
      "markup.bold"?: string;
      "markup.changed"?: string;
      "markup.deleted"?: string;
      "markup.heading"?: string;
      "markup.inline.raw"?: string;
      "markup.inserted"?: string;
      "markup.italic"?: string;
      "markup.list"?: string;
      "markup.quote"?: string;
      "markup.raw"?: string;
      "markup.underline"?: string;
      "markup.underline.link"?: string;
      meta?: string;
      "meta.block"?: string;
      "meta.class"?: string;
      "meta.function"?: string;
      "meta.function-call"?: string;
      "meta.method-call"?: string;
      "meta.preprocessor"?: string;
      "meta.return-type"?: string;
      "meta.selector"?: string;
      "meta.tag"?: string;
      "meta.type.annotation"?: string;
      "punctuation.definition.comment"?: string;
      "punctuation.definition.string"?: string;
      "punctuation.definition.variable"?: string;
      "punctuation.section.embedded"?: string;
      storage?: string;
      "storage.modifier"?: string;
      "storage.type"?: string;
      string?: string;
      "string.interpolated"?: string;
      "string.other"?: string;
      "string.quoted"?: string;
      "string.regexp"?: string;
      support?: string;
      "support.class"?: string;
      "support.constant"?: string;
      "support.function"?: string;
      "support.other"?: string;
      "support.type"?: string;
      "support.variable"?: string;
      variable?: string;
      "variable.function"?: string;
      "variable.language"?: string;
      "variable.name"?: string;
      "variable.other"?: string;
      "variable.parameter"?: string;
    };
    ui?: {
      background?: string;
      primary?: string;
      "primary-light"?: string;
      "primary-dark"?: string;
      secondary?: string;
      "secondary-light"?: string;
      "secondary-dark"?: string;
      "background-dark"?: string;
      "background-light"?: string;
      text?: string;
      selection?: string;
      border?: string;
      link?: string;
      "link-visited"?: string;
      "button-background"?: string;
      "button-background-hover"?: string;
      "button-text"?: string;
    };
  };
}
